### ISSUE TITLE
EPIC: Investigate linking monitoring into Hub

### ISSUE THREAD

**Issue by rickwilliams391** [appvia/appvia-hub#57]
There are different avenues of monitoring
- [ ] platform monitoring for our own components i.e. agents, the hub, clusters etc. 
- [ ] project monitoring and how they will manage their own metrics / alerts
- [ ] dashboards on how to manage what visually is displayed
- [ ] authentication to the relevant dashboard for isolation

Some of the above at some point will need to factor in multiple clusters, but for MVP it would be 1 cluster.

**Comment by jon-shanks** [comment]
closing this ticket due to duplicates #117 #86
